name: pymc311
channels:
  - conda-forge
dependencies:
  - pymc
  - python=3.11
  - arviz
  - ipykernel
  - ipywidgets
  - scipy
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - bambi
  - statsmodels
